[package]
name = "microgradr"
version = "0.1.0"
edition = "2021"
authors = ["Elian Gidoni <elianmdp@gmail.com>"]

[dependencies]
thiserror = "1.0"
rand = "0.8"
rand_chacha = "0.3"

[dev-dependencies]
mockall = "0.12.1"
serial_test = "*"
